#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  May 16, 2023 03:45:44 PM EDT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m105" -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 600x450+660+210
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list selected $vTcl(actual_gui_bg) active $vTcl(tabbg1) !active $vTcl(tabbg2)]
    ttk::style map TNotebook.Tab -foreground [list selected $vTcl(actual_gui_fg) active $vTcl(tabfg1) !active $vTcl(tabfg2)]
    ttk::notebook "$top.tNo47" \
        -width 584 -height 436 -takefocus {} 
    vTcl:DefineAlias "$top.tNo47" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Frame -background $vTcl(actual_gui_bg)
    ttk::style configure Frame -foreground $vTcl(actual_gui_fg)
    ttk::style configure Frame -font "$vTcl(actual_gui_font_dft_desc)"
    frame "$top.tNo47.t0" \
        -background #8080ff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor #d70428 
    vTcl:DefineAlias "$top.tNo47.t0" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $top.tNo47 add $top.tNo47.t0 \
        -padding 0 -sticky nsew -state normal -text "Garage" -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo47.t0
    ttk::style configure Button -background $vTcl(actual_gui_bg)
    ttk::style configure Button -foreground $vTcl(actual_gui_fg)
    ttk::style configure Button -font "$vTcl(actual_gui_font_dft_desc)"
    button "$site_4_0.but49" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Déséréaliser" 
    vTcl:DefineAlias "$site_4_0.but49" "Button1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Button -background $vTcl(actual_gui_bg)
    ttk::style configure Button -foreground $vTcl(actual_gui_fg)
    ttk::style configure Button -font "$vTcl(actual_gui_font_dft_desc)"
    button "$site_4_0.but50" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "séréaliser" 
    vTcl:DefineAlias "$site_4_0.but50" "Button2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Entry -background $vTcl(actual_gui_bg)
    ttk::style configure Entry -foreground $vTcl(actual_gui_fg)
    ttk::style configure Entry -font "$vTcl(actual_gui_font_dft_desc)"
    entry "$site_4_0.ent51" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 224 
    vTcl:DefineAlias "$site_4_0.ent51" "Entry1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$site_4_0.lab52" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -text "Fichier:" 
    vTcl:DefineAlias "$site_4_0.lab52" "Label1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe "$site_4_0.tLa53" \
        -text "infos garage" -width 470 -height 175 
    vTcl:DefineAlias "$site_4_0.tLa53" "TLabelframe1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_5_0 $site_4_0.tLa53
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$site_5_0.lab54" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -text "Nom:" 
    vTcl:DefineAlias "$site_5_0.lab54" "Label2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$site_5_0.lab55" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -text "Téléphone:" 
    vTcl:DefineAlias "$site_5_0.lab55" "Label3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$site_5_0.lab56" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -text "Adresse:" 
    vTcl:DefineAlias "$site_5_0.lab56" "Label4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Entry -background $vTcl(actual_gui_bg)
    ttk::style configure Entry -foreground $vTcl(actual_gui_fg)
    ttk::style configure Entry -font "$vTcl(actual_gui_font_dft_desc)"
    entry "$site_5_0.ent57" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 164 
    vTcl:DefineAlias "$site_5_0.ent57" "Entry2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Entry -background $vTcl(actual_gui_bg)
    ttk::style configure Entry -foreground $vTcl(actual_gui_fg)
    ttk::style configure Entry -font "$vTcl(actual_gui_font_dft_desc)"
    entry "$site_5_0.ent58" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 164 
    vTcl:DefineAlias "$site_5_0.ent58" "Entry3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Entry -background $vTcl(actual_gui_bg)
    ttk::style configure Entry -foreground $vTcl(actual_gui_fg)
    ttk::style configure Entry -font "$vTcl(actual_gui_font_dft_desc)"
    entry "$site_5_0.ent59" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 164 
    vTcl:DefineAlias "$site_5_0.ent59" "Entry4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Button -background $vTcl(actual_gui_bg)
    ttk::style configure Button -foreground $vTcl(actual_gui_fg)
    ttk::style configure Button -font "$vTcl(actual_gui_font_dft_desc)"
    button "$site_5_0.but60" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "créer garage" 
    vTcl:DefineAlias "$site_5_0.but60" "Button3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_5_0.lab54 \
        -in $site_5_0 -x 0 -relx 0.17 -y 0 -rely 0.171 -width 0 \
        -relwidth 0.072 -height 0 -relheight 0.12 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab55 \
        -in $site_5_0 -x 0 -relx 0.149 -y 0 -rely 0.686 -width 0 \
        -relwidth 0.136 -height 0 -relheight 0.12 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab56 \
        -in $site_5_0 -x 0 -relx 0.17 -y 0 -rely 0.4 -width 0 -relwidth 0.115 \
        -height 0 -relheight 0.12 -anchor nw -bordermode ignore 
    place $site_5_0.ent57 \
        -in $site_5_0 -x 0 -relx 0.298 -y 0 -rely 0.171 -width 164 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent58 \
        -in $site_5_0 -x 0 -relx 0.298 -y 0 -rely 0.4 -width 164 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent59 \
        -in $site_5_0 -x 0 -relx 0.298 -y 0 -rely 0.686 -width 164 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but60 \
        -in $site_5_0 -x 0 -relx 0.34 -y 0 -rely 0.857 -width 107 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but49 \
        -in $site_4_0 -x 0 -relx 0.138 -y 0 -rely 0.78 -width 117 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but50 \
        -in $site_4_0 -x 0 -relx 0.5 -y 0 -rely 0.78 -width 137 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent51 \
        -in $site_4_0 -x 0 -relx 0.293 -y 0 -rely 0.634 -width 224 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab52 \
        -in $site_4_0 -x 0 -relx 0.207 -y 0 -rely 0.61 -width 0 \
        -relwidth 0.076 -height 0 -relheight 0.076 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tLa53 \
        -in $site_4_0 -x 0 -relx 0.086 -y 0 -rely 0.073 -width 0 \
        -relwidth 0.81 -height 0 -relheight 0.427 -anchor nw \
        -bordermode ignore 
    ttk::style configure Frame -background $vTcl(actual_gui_bg)
    ttk::style configure Frame -foreground $vTcl(actual_gui_fg)
    ttk::style configure Frame -font "$vTcl(actual_gui_font_dft_desc)"
    frame "$top.tNo47.t1" \
        -background #0080ff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo47.t1" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $top.tNo47 add $top.tNo47.t1 \
        -padding 0 -sticky nsew -state normal -text "voiture" -image {} \
        -compound left -underline -1 
    set site_4_1  $top.tNo47.t1
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe "$site_4_1.tLa61" \
        -text "Infos voiture" -width 580 -height 155 
    vTcl:DefineAlias "$site_4_1.tLa61" "TLabelframe2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_5_0 $site_4_1.tLa61
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$site_5_0.lab63" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -text "Num Plaque" 
    vTcl:DefineAlias "$site_5_0.lab63" "Label5" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$site_5_0.lab64" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -text "Marque" 
    vTcl:DefineAlias "$site_5_0.lab64" "Label6" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$site_5_0.lab65" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -text "Couleur" 
    vTcl:DefineAlias "$site_5_0.lab65" "Label7" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Entry -background $vTcl(actual_gui_bg)
    ttk::style configure Entry -foreground $vTcl(actual_gui_fg)
    ttk::style configure Entry -font "$vTcl(actual_gui_font_dft_desc)"
    entry "$site_5_0.ent66" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 174 
    vTcl:DefineAlias "$site_5_0.ent66" "Entry5" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Entry -background $vTcl(actual_gui_bg)
    ttk::style configure Entry -foreground $vTcl(actual_gui_fg)
    ttk::style configure Entry -font "$vTcl(actual_gui_font_dft_desc)"
    entry "$site_5_0.ent67" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 174 
    vTcl:DefineAlias "$site_5_0.ent67" "Entry6" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Entry -background $vTcl(actual_gui_bg)
    ttk::style configure Entry -foreground $vTcl(actual_gui_fg)
    ttk::style configure Entry -font "$vTcl(actual_gui_font_dft_desc)"
    entry "$site_5_0.ent68" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 174 
    vTcl:DefineAlias "$site_5_0.ent68" "Entry7" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$site_5_0.lab69" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -text "Modèle:" 
    vTcl:DefineAlias "$site_5_0.lab69" "Label8" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$site_5_0.lab70" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -text "Année:" 
    vTcl:DefineAlias "$site_5_0.lab70" "Label9" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Entry -background $vTcl(actual_gui_bg)
    ttk::style configure Entry -foreground $vTcl(actual_gui_fg)
    ttk::style configure Entry -font "$vTcl(actual_gui_font_dft_desc)"
    entry "$site_5_0.ent71" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 104 
    vTcl:DefineAlias "$site_5_0.ent71" "Entry8" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Entry -background $vTcl(actual_gui_bg)
    ttk::style configure Entry -foreground $vTcl(actual_gui_fg)
    ttk::style configure Entry -font "$vTcl(actual_gui_font_dft_desc)"
    entry "$site_5_0.ent72" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 104 
    vTcl:DefineAlias "$site_5_0.ent72" "Entry9" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_5_0.lab63 \
        -in $site_5_0 -x 0 -relx 0.034 -y 0 -rely 0.194 -width 0 \
        -relwidth 0.129 -height 0 -relheight 0.129 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab64 \
        -in $site_5_0 -x 0 -relx 0.053 -y 0 -rely 0.361 -width 0 \
        -relwidth 0.095 -height 0 -relheight 0.129 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab65 \
        -in $site_5_0 -x 0 -relx 0.053 -y 0 -rely 0.542 -width 0 \
        -relwidth 0.095 -height 0 -relheight 0.129 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent66 \
        -in $site_5_0 -x 0 -relx 0.175 -y 0 -rely 0.182 -width 174 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent67 \
        -in $site_5_0 -x 0 -relx 0.175 -y 0 -rely 0.364 -width 174 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent68 \
        -in $site_5_0 -x 0 -relx 0.175 -y 0 -rely 0.545 -width 174 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab69 \
        -in $site_5_0 -x 0 -relx 0.672 -y 0 -rely 0.452 -width 0 \
        -relwidth 0.095 -height 0 -relheight 0.129 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab70 \
        -in $site_5_0 -x 0 -relx 0.672 -y 0 -rely 0.581 -width 0 \
        -relwidth 0.078 -height 0 -relheight 0.187 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent71 \
        -in $site_5_0 -x 0 -relx 0.772 -y 0 -rely 0.424 -width 104 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent72 \
        -in $site_5_0 -x 0 -relx 0.772 -y 0 -rely 0.606 -width 104 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe "$site_4_1.tLa62" \
        -text "infos propriétaire" -width 580 -height 185 
    vTcl:DefineAlias "$site_4_1.tLa62" "TLabelframe3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_5_0 $site_4_1.tLa62
    ttk::style configure Entry -background $vTcl(actual_gui_bg)
    ttk::style configure Entry -foreground $vTcl(actual_gui_fg)
    ttk::style configure Entry -font "$vTcl(actual_gui_font_dft_desc)"
    entry "$site_5_0.ent73" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 204 
    vTcl:DefineAlias "$site_5_0.ent73" "Entry10" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Entry -background $vTcl(actual_gui_bg)
    ttk::style configure Entry -foreground $vTcl(actual_gui_fg)
    ttk::style configure Entry -font "$vTcl(actual_gui_font_dft_desc)"
    entry "$site_5_0.ent74" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 254 
    vTcl:DefineAlias "$site_5_0.ent74" "Entry11" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Entry -background $vTcl(actual_gui_bg)
    ttk::style configure Entry -foreground $vTcl(actual_gui_fg)
    ttk::style configure Entry -font "$vTcl(actual_gui_font_dft_desc)"
    entry "$site_5_0.ent75" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 254 
    vTcl:DefineAlias "$site_5_0.ent75" "Entry12" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Entry -background $vTcl(actual_gui_bg)
    ttk::style configure Entry -foreground $vTcl(actual_gui_fg)
    ttk::style configure Entry -font "$vTcl(actual_gui_font_dft_desc)"
    entry "$site_5_0.ent76" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 204 
    vTcl:DefineAlias "$site_5_0.ent76" "Entry13" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$site_5_0.lab77" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -text "Nom:" 
    vTcl:DefineAlias "$site_5_0.lab77" "Label10" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$site_5_0.lab78" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -text "Prénom" 
    vTcl:DefineAlias "$site_5_0.lab78" "Label11" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$site_5_0.lab79" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -text "Courriel" 
    vTcl:DefineAlias "$site_5_0.lab79" "Label12" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$site_5_0.lab80" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -text "Téléphone" 
    vTcl:DefineAlias "$site_5_0.lab80" "Label13" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_5_0.ent73 \
        -in $site_5_0 -x 0 -relx 0.179 -y 0 -rely 0.205 -width 204 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent74 \
        -in $site_5_0 -x 0 -relx 0.179 -y 0 -rely 0.411 -width 254 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent75 \
        -in $site_5_0 -x 0 -relx 0.179 -y 0 -rely 0.562 -width 254 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent76 \
        -in $site_5_0 -x 0 -relx 0.179 -y 0 -rely 0.718 -width 204 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab77 \
        -in $site_5_0 -x 0 -relx 0.069 -y 0 -rely 0.216 -width 0 \
        -relwidth 0.06 -height 0 -relheight 0.108 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab78 \
        -in $site_5_0 -x 0 -relx 0.052 -y 0 -rely 0.432 -width 0 \
        -relwidth 0.078 -height 0 -relheight 0.108 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab79 \
        -in $site_5_0 -x 0 -relx 0.052 -y 0 -rely 0.541 -width 0 \
        -relwidth 0.095 -height 0 -relheight 0.108 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab80 \
        -in $site_5_0 -x 0 -relx 0.034 -y 0 -rely 0.703 -width 0 \
        -relwidth 0.112 -height 0 -relheight 0.108 -anchor nw \
        -bordermode ignore 
    ttk::style configure Button -background $vTcl(actual_gui_bg)
    ttk::style configure Button -foreground $vTcl(actual_gui_fg)
    ttk::style configure Button -font "$vTcl(actual_gui_font_dft_desc)"
    button "$site_4_1.but81" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Ajouter" 
    vTcl:DefineAlias "$site_4_1.but81" "Button4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Button -background $vTcl(actual_gui_bg)
    ttk::style configure Button -foreground $vTcl(actual_gui_fg)
    ttk::style configure Button -font "$vTcl(actual_gui_font_dft_desc)"
    button "$site_4_1.but82" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "rechercher" 
    vTcl:DefineAlias "$site_4_1.but82" "Button5" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_4_1.tLa61 \
        -in $site_4_1 -x 0 -y 0 -rely 0.049 -width 0 -relwidth 1 -height 0 \
        -relheight 0.378 -anchor nw -bordermode ignore 
    place $site_4_1.tLa62 \
        -in $site_4_1 -x 0 -y 0 -rely 0.439 -width 0 -relwidth 1 -height 0 \
        -relheight 0.451 -anchor nw -bordermode ignore 
    place $site_4_1.but81 \
        -in $site_4_1 -x 0 -relx 0.121 -y 0 -rely 0.927 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but82 \
        -in $site_4_1 -x 0 -relx 0.586 -y 0 -rely 0.927 -width 97 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure Frame -background $vTcl(actual_gui_bg)
    ttk::style configure Frame -foreground $vTcl(actual_gui_fg)
    ttk::style configure Frame -font "$vTcl(actual_gui_font_dft_desc)"
    frame "$top.tNo47.t2" \
        -background #008040 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo47.t2" "TNotebook1_t3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $top.tNo47 add $top.tNo47.t2 \
        -padding 0 -sticky nsew -state normal -text "réparation" -image {} \
        -compound left -underline -1 
    set site_4_2  $top.tNo47.t2
    ttk::style configure Entry -background $vTcl(actual_gui_bg)
    ttk::style configure Entry -foreground $vTcl(actual_gui_fg)
    ttk::style configure Entry -font "$vTcl(actual_gui_font_dft_desc)"
    entry "$site_4_2.ent83" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 114 
    vTcl:DefineAlias "$site_4_2.ent83" "Entry14" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Entry -background $vTcl(actual_gui_bg)
    ttk::style configure Entry -foreground $vTcl(actual_gui_fg)
    ttk::style configure Entry -font "$vTcl(actual_gui_font_dft_desc)"
    entry "$site_4_2.ent84" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 10 
    vTcl:DefineAlias "$site_4_2.ent84" "Entry15" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$site_4_2.lab85" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -text "Numéro téchnicien:" 
    vTcl:DefineAlias "$site_4_2.lab85" "Label14" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$site_4_2.lab86" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -text "Numéro plaque:" 
    vTcl:DefineAlias "$site_4_2.lab86" "Label15" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Labelframe -background $vTcl(actual_gui_bg)
    ttk::style configure Labelframe -foreground $vTcl(actual_gui_fg)
    ttk::style configure Labelframe -font "$vTcl(actual_gui_font_dft_desc)"
    labelframe "$site_4_2.lab87" \
        -font "TkDefaultFont" -foreground $vTcl(actual_gui_fg) \
        -text "Labelframe" -background $vTcl(actual_gui_bg) -height 165 \
        -width 550 
    vTcl:DefineAlias "$site_4_2.lab87" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    set site_5_0 $site_4_2.lab87
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$site_5_0.lab90" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -text "Code:" 
    vTcl:DefineAlias "$site_5_0.lab90" "Label16" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$site_5_0.lab91" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -text "Description:" 
    vTcl:DefineAlias "$site_5_0.lab91" "Label17" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$site_5_0.lab92" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -text "Date:" 
    vTcl:DefineAlias "$site_5_0.lab92" "Label18" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$site_5_0.lab93" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -text "Montant:" 
    vTcl:DefineAlias "$site_5_0.lab93" "Label19" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Entry -background $vTcl(actual_gui_bg)
    ttk::style configure Entry -foreground $vTcl(actual_gui_fg)
    ttk::style configure Entry -font "$vTcl(actual_gui_font_dft_desc)"
    entry "$site_5_0.ent94" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 154 
    vTcl:DefineAlias "$site_5_0.ent94" "Entry16" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Entry -background $vTcl(actual_gui_bg)
    ttk::style configure Entry -foreground $vTcl(actual_gui_fg)
    ttk::style configure Entry -font "$vTcl(actual_gui_font_dft_desc)"
    entry "$site_5_0.ent95" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 234 
    vTcl:DefineAlias "$site_5_0.ent95" "Entry17" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Entry -background $vTcl(actual_gui_bg)
    ttk::style configure Entry -foreground $vTcl(actual_gui_fg)
    ttk::style configure Entry -font "$vTcl(actual_gui_font_dft_desc)"
    entry "$site_5_0.ent96" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 84 
    vTcl:DefineAlias "$site_5_0.ent96" "Entry18" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Entry -background $vTcl(actual_gui_bg)
    ttk::style configure Entry -foreground $vTcl(actual_gui_fg)
    ttk::style configure Entry -font "$vTcl(actual_gui_font_dft_desc)"
    entry "$site_5_0.ent97" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 114 
    vTcl:DefineAlias "$site_5_0.ent97" "Entry19" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_5_0.lab90 \
        -in $site_5_0 -x 0 -relx 0.109 -y 0 -rely 0.182 -width 0 \
        -relwidth 0.062 -height 0 -relheight 0.127 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab91 \
        -in $site_5_0 -x 0 -relx 0.055 -y 0 -rely 0.364 -width 0 \
        -relwidth 0.135 -height 0 -relheight 0.127 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab92 \
        -in $site_5_0 -x 0 -relx 0.109 -y 0 -rely 0.667 -width 0 \
        -relwidth 0.062 -height 0 -relheight 0.127 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab93 \
        -in $site_5_0 -x 0 -relx 0.545 -y 0 -rely 0.667 -width 0 \
        -relwidth 0.098 -height 0 -relheight 0.188 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent94 \
        -in $site_5_0 -x 0 -relx 0.182 -y 0 -rely 0.182 -width 154 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent95 \
        -in $site_5_0 -x 0 -relx 0.182 -y 0 -rely 0.364 -width 234 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent96 \
        -in $site_5_0 -x 0 -relx 0.182 -y 0 -rely 0.667 -width 84 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent97 \
        -in $site_5_0 -x 0 -relx 0.655 -y 0 -rely 0.667 -width 114 \
        -relwidth 0 -height 40 -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure Button -background $vTcl(actual_gui_bg)
    ttk::style configure Button -foreground $vTcl(actual_gui_fg)
    ttk::style configure Button -font "$vTcl(actual_gui_font_dft_desc)"
    button "$site_4_2.but88" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Ajouter" 
    vTcl:DefineAlias "$site_4_2.but88" "Button6" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Button -background $vTcl(actual_gui_bg)
    ttk::style configure Button -foreground $vTcl(actual_gui_fg)
    ttk::style configure Button -font "$vTcl(actual_gui_font_dft_desc)"
    button "$site_4_2.but89" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "supprimer" 
    vTcl:DefineAlias "$site_4_2.but89" "Button7" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_4_2.ent83 \
        -in $site_4_2 -x 0 -relx 0.241 -y 0 -rely 0.146 -width 114 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.ent84 \
        -in $site_4_2 -x 0 -relx 0.241 -y 0 -rely 0.22 -width 84 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.lab85 \
        -in $site_4_2 -x 0 -relx 0.034 -y 0 -rely 0.22 -width 0 \
        -relwidth 0.197 -height 0 -relheight 0.051 -anchor nw \
        -bordermode ignore 
    place $site_4_2.lab86 \
        -in $site_4_2 -x 0 -relx 0.069 -y 0 -rely 0.146 -width 0 \
        -relwidth 0.162 -height 0 -relheight 0.051 -anchor nw \
        -bordermode ignore 
    place $site_4_2.lab87 \
        -in $site_4_2 -x 0 -relx 0.017 -y 0 -rely 0.39 -width 0 \
        -relwidth 0.948 -height 0 -relheight 0.402 -anchor nw \
        -bordermode ignore 
    place $site_4_2.but88 \
        -in $site_4_2 -x 0 -relx 0.293 -y 0 -rely 0.878 -width 87 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but89 \
        -in $site_4_2 -x 0 -relx 0.552 -y 0 -rely 0.878 -width 87 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure Frame -background $vTcl(actual_gui_bg)
    ttk::style configure Frame -foreground $vTcl(actual_gui_fg)
    ttk::style configure Frame -font "$vTcl(actual_gui_font_dft_desc)"
    frame "$top.tNo47.t3" \
        -background #8080c0 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo47.t3" "TNotebook1_t4" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $top.tNo47 add $top.tNo47.t3 \
        -padding 0 -sticky nsew -state normal -text "consultation" -image {} \
        -compound left -underline -1 
    set site_4_3  $top.tNo47.t3
    ttk::style configure Entry -background $vTcl(actual_gui_bg)
    ttk::style configure Entry -foreground $vTcl(actual_gui_fg)
    ttk::style configure Entry -font "$vTcl(actual_gui_font_dft_desc)"
    entry "$site_4_3.ent99" \
        -background white -disabledforeground #a3a3a3 -font "TkFixedFont" \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 184 
    vTcl:DefineAlias "$site_4_3.ent99" "Entry21" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Button -background $vTcl(actual_gui_bg)
    ttk::style configure Button -foreground $vTcl(actual_gui_fg)
    ttk::style configure Button -font "$vTcl(actual_gui_font_dft_desc)"
    button "$site_4_3.but100" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Afficher réparation" 
    vTcl:DefineAlias "$site_4_3.but100" "Button8" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$site_4_3.lab101" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -text "Numéro plaque:" 
    vTcl:DefineAlias "$site_4_3.lab101" "Label20" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure Label -background $vTcl(actual_gui_bg)
    ttk::style configure Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure Label -font "$vTcl(actual_gui_font_dft_desc)"
    label "$site_4_3.lab102" \
        -activeforeground SystemButtonText -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) -text "Marque Voiture:" 
    vTcl:DefineAlias "$site_4_3.lab102" "Label21" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    ttk::style configure TCombobox -background $vTcl(actual_gui_bg)
    ttk::style configure TCombobox -foreground $vTcl(actual_gui_fg)
    ttk::style configure TCombobox -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::combobox "$site_4_3.tCo104" \
        -font "TkTextFont" -textvariable "combobox" -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_3.tCo104" "TCombobox1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    place $site_4_3.ent99 \
        -in $site_4_3 -x 0 -relx 0.293 -y 0 -rely 0.22 -width 184 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_3.but100 \
        -in $site_4_3 -x 0 -relx 0.69 -y 0 -rely 0.122 -width 147 -relwidth 0 \
        -height 54 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_3.lab101 \
        -in $site_4_3 -x 0 -relx 0.103 -y 0 -rely 0.049 -width 0 \
        -relwidth 0.179 -height 0 -relheight 0.076 -anchor nw \
        -bordermode ignore 
    place $site_4_3.lab102 \
        -in $site_4_3 -x 0 -relx 0.103 -y 0 -rely 0.22 -width 0 \
        -relwidth 0.162 -height 0 -relheight 0.076 -anchor nw \
        -bordermode ignore 
    place $site_4_3.tCo104 \
        -in $site_4_3 -x 0 -relx 0.293 -y 0 -rely 0.049 -width 0 \
        -relwidth 0.316 -height 0 -relheight 0.1 -anchor nw \
        -bordermode ignore 
    ttk::style configure Menu -background $vTcl(actual_gui_bg)
    ttk::style configure Menu -foreground $vTcl(actual_gui_fg)
    ttk::style configure Menu -font "$vTcl(actual_gui_font_dft_desc)"
    menu "$top.m105" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font "TkMenuFont" -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo47 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.022 -width 0 -relwidth 0.973 \
        -height 0 -relheight 0.969 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

